### ISSUE TITLE
UniFi controller should adopt the certificate and hostname from pfsense

### ISSUE THREAD

**Issue by cqr** [unofficial-unifi/unifi-pfsense#104] opened 2018-03-27 22:24 UTC
I have an automated way to do the certificate, likely the hostname is trivial.

Mostly looking for confirmation that this kind of integration is welcome.

**Comment by shaneallgeier** [comment] 2018-03-27 23:47
I can speak for @gozoinks but I know that I'm very interested in this potential feature.

**Comment by dvdp** [comment] 2018-03-28 12:54
I have ACME installed on my pfSense box and a script that imports the Let's Encrypt cert into the UniFi controller - works like a charm. Setting Controller Hostname to the hostname of the pfSense box should be trivial indeed - actually if you run it on the same box, the only logical choice is to make it the same name.

**Comment by gozoinks** [comment] 2018-03-28 13:11
Keeping the hostnames independent—specifically, keeping the UniFi controller hostname “unifi” — means new devices automatically discover and inform the controller. Leaving the UniFi controller  hostname at its default “unifi“ and the firewall hostname at its default “firewall”,  means everything works out of the box, and all the administrator has to do is add the hostnames to the DNS resolver. That seems logical to me. 

In any case, this becomes a matter of preference or policy for a given network, and I’m not sure there is a benefit to changing hostnames for every installation. 

Certificates, however, sure. Can your script generate a certificate for unifi.<local domain>?

**Comment by chrisrhoden** [comment] 2018-03-28 13:16
It could but there would be limited benefit since UniFi Controller will automatically install a self-signed certificate and the purpose of this is to automatically install a trusted certificate. We could consider something like let's encrypt but that generally requires that you are signing a publicly addressable hostname which I am not.

I didn't realize the discovery relied on the controller having that hostname - I wonder if we could handle that by automatically adding the record to pfsense's dns resolver. In any event, sounds like this is more complicated than I thought, while it worked well for me it may not be generally applicable.

**Comment by xatage** [comment] 2018-03-28 13:18
> actually if you run it on the same box, the only logical choice is to make it the same name

Why? I gave my controller a virtual IP and so it's not a problem with the own hostname. You could also just add a hostname to the resolver, but with a virtual IP you can even redirect the https port 443 to unifi's 8443 in the NAT settings and have a nice URL :)

But yes, I have a script for that like @dvdp , too. It run's right after a Let's Encrypt certificate was renewed, importing the new certificates and restarting my controller.

**Comment by dvdp** [comment] 2018-03-28 13:33
@xatage - you are absolutely right - my approach was just aiming at using the same IP and FQDN for pfSense and UniFi - works fine for me. Initially I created the cert for pfSense only so with just one domain, by using the same hostname for UniFi I did not need to create a new cert.
As for the discovery: I just added 'unifi' to the host overrides in the DNS Forwarder and set the IP to the IP of pfSense/UniFi box - devices are discovered nicely ....

**Comment by gozoinks** [comment] 2018-03-28 15:15
Adding a 'unifi' record in DNS seems like a good idea.

I really like this line of discussion. Linking hostnames, certificates, and DNS records is a great way to make UniFi controller more seamlessly integrated with pfSense. I treat them as separate entities in my own installations, but I can totally see the value in treating them more as one, as a kind of DIY USG. 

Doing that well involves UI for configuring the way UniFi controller and pfSense coexist.

But this brings me back to my notes in the README. The script here is portable to many BSD-based systems and requires no other infrastructure, running equally well on FreeNAS and plain old BSD. A pfSense GUI plugin depends on pfSense (and varies by version even), and developing that requires forking/branching the plugin repo. To me, therefore, the thing that makes sense is to fork the pfSense plugin repo to develop a pfSense package that provides a UI that bridges between pfSense and this script (or a package based on this script), or something to similar effect.

Otherwise, we run the risk of breaking compatibility with non-pfSense systems, introducing unexpected behavior, and adding the complexity of maintaining compatibility with third-party APIs.

**Comment by MattDahEpic** [comment] 2019-06-02 14:52
To keep the compatibility with all systems, the script could detect if the system is indeed pfSense and do the certificate linking automatically but present a selection (where is your certificate file?) for other systems so that everyone can have the script at least automatically install the certificate into the controller.
This is super important for those running pfSense and Unifi on the same machine with HTTPS since pfSense sends HSTS headers and you can't access Unifi with an invalid certificate on the same hostname by default.

**Comment by tong2x** [comment] 2022-07-08 05:56
no updates since, closing for now

**Closed by tong2x** 2022-07-08 05:56 UTC
